version: '3'
services:
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./dist:/app/dist
    environment:
      VIRTUAL_HOST: api.andyspotting.docker
      BASE_URL: http://api.andyspotting.docker
      IMAGES_URL: http://images.ajmay.docker
      IMAGES_SECRET: pa$$word

  watch:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./dist:/app/dist
      - ./src:/app/src
      - ./.babelrc:/app/.babelrc
    command: npm run watch
